import { FormEvent, useEffect, useMemo, useState } from 'react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { ArrowDownRight, ArrowUpRight, BarChart3, Boxes, CalendarDays, Check, ChevronDown, CircleDollarSign, Download, FileBarChart, LayoutDashboard, Menu, Plus, Receipt, Search, Settings, ShoppingBag, UserRound, WalletCards, X } from 'lucide-react'
import { supabase } from './lib/supabase'

type Page='Dashboard'|'Ventas'|'Productos'|'Gastos'|'Pagos'|'Estadísticas'|'Reportes'
type Sale={id:string;date:string;product:string;quantity:number;price:number;cost:number;method:string;status:string}
type Product={id:string;name:string;price:number;cost:number;units:number}
type Expense={id:string;name:string;category:string;amount:number;date:string}

const products:Product[]=[{id:'p1',name:'Plan Growth',price:149,cost:34,units:86},{id:'p2',name:'Consultoría estratégica',price:390,cost:120,units:34},{id:'p3',name:'Plantilla Finance OS',price:79,cost:8,units:142},{id:'p4',name:'Plan Starter',price:49,cost:12,units:194}]
const initialSales:Sale[]=[
 {id:'NV-1048',date:'2026-08-01',product:'Plan Growth',quantity:2,price:149,cost:34,method:'Mercado Pago',status:'Pagado'},
 {id:'NV-1047',date:'2026-08-01',product:'Consultoría estratégica',quantity:1,price:390,cost:120,method:'Transferencia',status:'Pagado'},
 {id:'NV-1046',date:'2026-07-31',product:'Plantilla Finance OS',quantity:3,price:79,cost:8,method:'Tarjeta',status:'Pendiente'},
 {id:'NV-1045',date:'2026-07-31',product:'Plan Starter',quantity:4,price:49,cost:12,method:'Mercado Pago',status:'Pagado'},
 {id:'NV-1044',date:'2026-07-30',product:'Plan Growth',quantity:1,price:149,cost:34,method:'Efectivo',status:'Pagado'}]
const expenses:Expense[]=[{id:'g1',name:'Campaña de adquisición',category:'Publicidad',amount:580,date:'2026-08-01'},{id:'g2',name:'Infraestructura cloud',category:'Hosting',amount:129,date:'2026-07-30'},{id:'g3',name:'Suite de diseño',category:'Herramientas',amount:46,date:'2026-07-28'},{id:'g4',name:'Comisiones de cobro',category:'Comisiones',amount:188,date:'2026-07-27'}]
const performance=[{day:'Lun',sales:1180,costs:310,profit:730},{day:'Mar',sales:1640,costs:420,profit:1060},{day:'Mié',sales:1420,costs:390,profit:880},{day:'Jue',sales:2180,costs:570,profit:1410},{day:'Vie',sales:1940,costs:510,profit:1240},{day:'Sáb',sales:2460,costs:620,profit:1590},{day:'Dom',sales:2320,costs:580,profit:1500}]
const navItems=[{name:'Dashboard' as Page,icon:LayoutDashboard},{name:'Ventas' as Page,icon:ShoppingBag},{name:'Productos' as Page,icon:Boxes},{name:'Gastos' as Page,icon:Receipt},{name:'Pagos' as Page,icon:WalletCards},{name:'Estadísticas' as Page,icon:BarChart3},{name:'Reportes' as Page,icon:FileBarChart}]
const money=new Intl.NumberFormat('es-AR',{style:'currency',currency:'USD',maximumFractionDigits:0})

export default function App(){
 const [page,setPage]=useState<Page>('Dashboard'),[menu,setMenu]=useState(false),[modal,setModal]=useState(false),[sales,setSales]=useState(initialSales),[live,setLive]=useState(false),[toast,setToast]=useState('')
 useEffect(()=>{supabase.from('sales_overview').select('*').limit(20).then(({data})=>{if(data?.length){setSales(data.map((r:any)=>({id:r.sale_number,date:r.sold_at.slice(0,10),product:r.product_name,quantity:r.quantity,price:Number(r.unit_price),cost:Number(r.unit_cost),method:r.payment_method,status:r.status})));setLive(true)}})},[])
 const navigate=(p:Page)=>{setPage(p);setMenu(false)}
 const success=(m:string)=>{setToast(m);setTimeout(()=>setToast(''),2600)}
 return <div className="shell">
  <aside className={menu?'open':''}><div className="logo"><img src="/brand/jcb-wordmark.png" alt="JCB Developement"/><button onClick={()=>setMenu(false)}><X/></button></div><div className="nav-label">GESTIÓN</div><nav>{navItems.map(({name,icon:Icon})=><button key={name} className={page===name?'active':''} onClick={()=>navigate(name)}><Icon/>{name}</button>)}</nav><div className="aside-bottom"><button><Settings/>Configuración</button><button><UserRound/>Perfil</button><div className="user"><div><img src="/brand/jb-mark.png" alt="JB"/></div><span><b>JCB Developement</b><small>Administrador</small></span></div></div></aside>
  <main><header><button className="hamb" onClick={()=>setMenu(true)}><Menu/></button><div><h1>{page}</h1><p>{page==='Dashboard'?'Todo lo importante de tu negocio, en un solo lugar.':'Gestioná y analizá la información de tu negocio.'}</p></div><div className="header-actions"><span className={'sync '+(live?'live':'')}><i/>{live?'Sincronizado':'Modo demo'}</span><button className="period"><CalendarDays/>Este mes<ChevronDown/></button>{['Ventas','Dashboard'].includes(page)&&<button className="primary" onClick={()=>setModal(true)}><Plus/>Agregar venta</button>}</div></header>
   {page==='Dashboard'&&<Dashboard sales={sales}/>} {page==='Ventas'&&<SalesPage sales={sales} open={()=>setModal(true)}/>} {page==='Productos'&&<ProductsPage/>} {page==='Gastos'&&<ExpensesPage/>} {page==='Pagos'&&<PaymentsPage/>} {page==='Estadísticas'&&<StatsPage/>} {page==='Reportes'&&<ReportsPage success={success}/>} 
  </main>{modal&&<SaleModal close={()=>setModal(false)} add={s=>{setSales([s,...sales]);setModal(false);success('Venta registrada correctamente')}}/>}{toast&&<div className="toast"><Check/>{toast}</div>}
 </div>
}

function Dashboard({sales}:{sales:Sale[]}){const salesTotal=performance.reduce((a,b)=>a+b.sales,0),cost=performance.reduce((a,b)=>a+b.costs,0),expense=943,net=salesTotal-cost-expense,margin=net/salesTotal*100;return <>
 <section className="metric-grid"><Metric title="Ventas" value={money.format(salesTotal)} change="12,8%" good/><Metric title="Ganancia neta" value={money.format(net)} change="9,4%" good/><Metric title="Costos" value={money.format(cost)} change="4,1%"/><Metric title="Gastos" value={money.format(expense)} change="2,6%"/><Metric title="Margen" value={margin.toFixed(1)+'%'} change="1,7%" good/></section>
 <section className="panel chart-panel"><div className="panel-head"><div><h2>Rendimiento financiero</h2><p>Ventas, costos y ganancias del período</p></div><div className="segmented"><button className="active">Día</button><button>Semana</button><button>Mes</button><button>Año</button></div></div><div className="chart-legends"><span><i className="purple"/>Ventas</span><span><i className="amber"/>Costos</span><span><i className="green"/>Ganancias</span></div><ResponsiveContainer width="100%" height={280}><AreaChart data={performance}><defs><linearGradient id="sales" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#5b55e7" stopOpacity=".2"/><stop offset="1" stopColor="#5b55e7" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="#edf0f3"/><XAxis dataKey="day" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip/><Area dataKey="sales" stroke="#5b55e7" strokeWidth={2.5} fill="url(#sales)"/><Area dataKey="costs" stroke="#e8a23a" strokeWidth={2} fill="transparent"/><Area dataKey="profit" stroke="#1eaa78" strokeWidth={2} fill="transparent"/></AreaChart></ResponsiveContainer><div className="chart-summary"><span>Ventas totales <b>{money.format(salesTotal)}</b></span><span>Costos totales <b>{money.format(cost)}</b></span><span>Ganancia neta <b>{money.format(net)}</b></span></div></section>
 <section className="insight-grid"><Insight label="Producto más vendido" value="Plan Starter" detail="194 unidades"/><Insight label="Mayor ganancia" value="Plan Growth" detail={money.format(9_890)}/><Insight label="Menor margen" value="Plan Starter" detail="75,5%"/><Insight label="Mejor día" value="Sábado" detail={money.format(2_460)}/></section><SalesTable sales={sales.slice(0,5)} title="Últimas ventas"/></>}

function Metric({title,value,change,good=false}:{title:string,value:string,change:string,good?:boolean}){return <article className="metric"><div className="metric-top"><span>{title}</span><CircleDollarSign/></div><strong>{value}</strong><div className={good?'change good':'change'}>{good?<ArrowUpRight/>:<ArrowDownRight/>}{change}<span>vs. período anterior</span></div></article>}
function Insight({label,value,detail}:{label:string,value:string,detail:string}){return <article className="insight"><span>{label}</span><b>{value}</b><small>{detail}</small></article>}
function SalesPage({sales,open}:{sales:Sale[],open:()=>void}){return <><Toolbar button="Nueva venta" action={open}/><SalesTable sales={sales} title="Todas las ventas"/></>}
function SalesTable({sales,title}:{sales:Sale[],title:string}){return <section className="panel table-panel"><div className="panel-head"><div><h2>{title}</h2><p>{sales.length} registros encontrados</p></div><button className="text-btn">Ver todas</button></div><div className="table-wrap"><table><thead><tr><th>FECHA</th><th>PRODUCTO</th><th>CANT.</th><th>PRECIO</th><th>COSTO</th><th>GANANCIA</th><th>MÉTODO</th><th>ESTADO</th></tr></thead><tbody>{sales.map(s=><tr key={s.id}><td><small>{s.id}</small>{new Date(s.date+'T12:00').toLocaleDateString('es-AR')}</td><td><b>{s.product}</b></td><td>{s.quantity}</td><td>{money.format(s.price*s.quantity)}</td><td>{money.format(s.cost*s.quantity)}</td><td className="profit">{money.format((s.price-s.cost)*s.quantity)}</td><td>{s.method}</td><td><Status value={s.status}/></td></tr>)}</tbody></table></div></section>}
function ProductsPage(){return <><Toolbar button="Agregar producto"/><section className="panel table-panel"><div className="panel-head"><div><h2>Catálogo de productos</h2><p>Rendimiento acumulado por producto</p></div></div><div className="table-wrap"><table><thead><tr><th>PRODUCTO</th><th>PRECIO</th><th>COSTO</th><th>GANANCIA/U.</th><th>MARGEN</th><th>UNIDADES</th><th>VENTAS TOTALES</th><th>GANANCIA TOTAL</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td><b>{p.name}</b></td><td>{money.format(p.price)}</td><td>{money.format(p.cost)}</td><td className="profit">{money.format(p.price-p.cost)}</td><td>{((p.price-p.cost)/p.price*100).toFixed(1)}%</td><td>{p.units}</td><td>{money.format(p.price*p.units)}</td><td className="profit">{money.format((p.price-p.cost)*p.units)}</td></tr>)}</tbody></table></div></section></>}
function ExpensesPage(){const cats=[{name:'Publicidad',value:580,color:'#5b55e7'},{name:'Comisiones',value:188,color:'#ef9a37'},{name:'Hosting',value:129,color:'#22ad7a'},{name:'Herramientas',value:46,color:'#8d94a0'}];return <><Toolbar button="Registrar gasto"/><section className="metric-grid four"><Metric title="Hoy" value={money.format(580)} change="12%"/><Metric title="Esta semana" value={money.format(943)} change="3,2%"/><Metric title="Este mes" value={money.format(2_870)} change="5,8%"/><Metric title="Este año" value={money.format(18_420)} change="8,1%"/></section><section className="two-cols"><div className="panel table-panel"><div className="panel-head"><div><h2>Gastos recientes</h2><p>Últimos movimientos registrados</p></div></div><div className="table-wrap"><table><thead><tr><th>GASTO</th><th>CATEGORÍA</th><th>FECHA</th><th>MONTO</th></tr></thead><tbody>{expenses.map(e=><tr key={e.id}><td><b>{e.name}</b></td><td>{e.category}</td><td>{e.date}</td><td>{money.format(e.amount)}</td></tr>)}</tbody></table></div></div><div className="panel pie"><div className="panel-head"><div><h2>Por categoría</h2><p>Distribución del período</p></div></div><ResponsiveContainer width="100%" height={240}><PieChart><Pie data={cats} dataKey="value" innerRadius={65} outerRadius={92} paddingAngle={3}>{cats.map(c=><Cell key={c.name} fill={c.color}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer>{cats.map(c=><div className="pie-row"><span><i style={{background:c.color}}/>{c.name}</span><b>{money.format(c.value)}</b></div>)}</div></section></>}
function PaymentsPage(){return <><Toolbar button="Registrar pago"/><section className="metric-grid four"><Metric title="Pagos recibidos" value={money.format(12_480)} change="9,2%" good/><Metric title="Pendientes" value={money.format(1_280)} change="2,1%"/><Metric title="Pagos realizados" value={money.format(3_640)} change="4,7%"/><Metric title="Balance" value={money.format(8_840)} change="11,4%" good/></section><section className="panel empty"><WalletCards/><h2>Central de pagos</h2><p>Registrá y controlá pagos recibidos y realizados desde un solo lugar.</p><button className="primary"><Plus/>Registrar pago</button></section></>}
function StatsPage(){return <><Toolbar/><section className="metric-grid four"><Metric title="Venta diaria promedio" value={money.format(1_877)} change="7,1%" good/><Metric title="Ganancia mensual" value={money.format(31_420)} change="12,2%" good/><Metric title="Costo mensual" value={money.format(9_870)} change="3,4%"/><Metric title="Margen promedio" value="68,4%" change="2,1%" good/></section><section className="panel chart-panel"><div className="panel-head"><div><h2>Evolución mensual</h2><p>Comparativa de los últimos 6 meses</p></div></div><ResponsiveContainer width="100%" height={350}><BarChart data={[{m:'Mar',v:31,g:18},{m:'Abr',v:38,g:23},{m:'May',v:42,g:26},{m:'Jun',v:48,g:30},{m:'Jul',v:51,g:32},{m:'Ago',v:58,g:37}]}><CartesianGrid vertical={false} stroke="#edf0f3"/><XAxis dataKey="m" axisLine={false}/><YAxis axisLine={false}/><Tooltip/><Bar dataKey="v" fill="#5b55e7" radius={[5,5,0,0]}/><Bar dataKey="g" fill="#aadfd0" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></section></>}
function ReportsPage({success}:{success:(s:string)=>void}){return <><Toolbar/><section className="report-hero panel"><div><span>REPORTE FINANCIERO</span><h2>Resumen de agosto 2026</h2><p>Estado consolidado de ingresos, costos y rentabilidad.</p></div><div className="export"><button onClick={()=>success('CSV generado')}><Download/>CSV</button><button onClick={()=>success('Excel generado')}><Download/>Excel</button><button className="primary" onClick={()=>success('PDF generado')}><Download/>PDF</button></div></section><section className="report-grid">{[['Ingresos','$58.420'],['Costos','$13.740'],['Gastos','$4.320'],['Ganancia bruta','$44.680'],['Ganancia neta','$40.360'],['Margen','69,1%']].map(x=><article><span>{x[0]}</span><b>{x[1]}</b></article>)}</section></>}
function Toolbar({button,action}:{button?:string,action?:()=>void}){return <div className="toolbar"><div className="search"><Search/><input placeholder="Buscar..."/></div><button className="filter"><CalendarDays/>Este mes<ChevronDown/></button>{button&&<button className="primary" onClick={action}><Plus/>{button}</button>}</div>}
function Status({value}:{value:string}){return <span className={'badge '+value.toLowerCase()}><i/>{value}</span>}
function SaleModal({close,add}:{close:()=>void,add:(s:Sale)=>void}){const [product,setProduct]=useState(products[0]),[qty,setQty]=useState(1),[price,setPrice]=useState(products[0].price),[cost,setCost]=useState(products[0].cost);const total=qty*price,profit=qty*(price-cost);function submit(e:FormEvent){e.preventDefault();add({id:'NV-'+(1049+Math.floor(Math.random()*100)),date:new Date().toISOString().slice(0,10),product:product.name,quantity:qty,price,cost,method:'Mercado Pago',status:'Pagado'})}return <div className="backdrop"><form className="modal" onSubmit={submit}><div className="modal-head"><div><h2>Nueva venta</h2><p>Registrá una operación en pocos segundos.</p></div><button type="button" onClick={close}><X/></button></div><label>Producto<select value={product.id} onChange={e=>{const p=products.find(x=>x.id===e.target.value)!;setProduct(p);setPrice(p.price);setCost(p.cost)}}>{products.map(p=><option value={p.id}>{p.name}</option>)}</select></label><div className="form-grid"><label>Cantidad<input type="number" min="1" value={qty} onChange={e=>setQty(+e.target.value)}/></label><label>Precio de venta<input type="number" value={price} onChange={e=>setPrice(+e.target.value)}/></label><label>Costo unitario<input type="number" value={cost} onChange={e=>setCost(+e.target.value)}/></label><label>Método<select><option>Mercado Pago</option><option>Transferencia</option><option>Efectivo</option><option>Tarjeta</option></select></label></div><label>Notas<textarea placeholder="Información adicional (opcional)"/></label><div className="calculation"><span>Subtotal<b>{money.format(total)}</b></span><span>Costo total<b>{money.format(cost*qty)}</b></span><span>Ganancia<b className="profit">{money.format(profit)}</b></span><span>Margen<b>{total?((profit/total)*100).toFixed(1):0}%</b></span></div><div className="modal-actions"><button type="button" onClick={close}>Cancelar</button><button className="primary">Guardar venta</button></div></form></div>}
